---
- name: Update package cache
  apt:
    update_cache: yes

- name: Install OpenVPN and Easy-RSA
  apt:
    name:
      - openvpn
      - easy-rsa
    state: present

- name: Init Easy-RSA folder
  file:
    path: "{{ easy_rsa_path }}"
    state: directory
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: Copy data to Easy-RSA folder
  copy:
    src: "/usr/share/easy-rsa/*"
    dest: "{{ easy_rsa_path }}/"
    owner: vagrant
    group: vagrant
    mode: '0644'
    remote_src: yes

- name: Init PKI
  command: ./easyrsa init-pki
  args:
    chdir: "{{ easy_rsa_path }}"
    creates: "{{ easy_rsa_path }}/pki"
  become_user: vagrant

- name: Create CA
  expect:
    command: ./easyrsa build-ca nopass
    responses:
      'Enter.*CA.*:': 'openvpn_ca\n'
    chdir: "{{ easy_rsa_path }}"
    creates: "{{ easy_rsa_pki_path }}/ca.crt"
  become_user: vagrant

- name: Create server
  expect:
    command: ./easyrsa gen-req server nopass
    responses:
      'Enter.*for server.*:': 'openvpn_server\n'
    chdir: "{{ easy_rsa_path }}"
    creates: "{{ easy_rsa_pki_path }}/private/server.key"
  become_user: vagrant

- name: Sign request
  expect:
    command: ./easyrsa sign-req server server
    responses:
      'Type the word.*to continue.*:': 'yes\n'
    chdir: "{{ easy_rsa_path }}"
    creates: "{{ easy_rsa_pki_path }}/issued/server.crt"
  become_user: vagrant

- name: Gen Diffie-Hellman params
  command: ./easyrsa gen-dh
  args:
    chdir: "{{ easy_rsa_path }}"
    creates: "{{ easy_rsa_pki_path }}/dh.pem"
  become_user: vagrant

- name: Gen TLS-key
  command: openvpn --genkey --secret pki/ta.key
  args:
    chdir: "{{ easy_rsa_path }}"
    creates: "{{ easy_rsa_pki_path }}/ta.key"
  become_user: vagrant

- name: Check OpenVPN dir
  file:
    path: /etc/openvpn
    state: directory
    mode: '0755'

- name: Copy OpenVPN files
  copy:
    src: "{{ item }}"
    dest: "{{ openvpn_config_path }}/"
    remote_src: yes
  with_items:
    - "{{ easy_rsa_pki_path }}/ca.crt"
    - "{{ easy_rsa_pki_path }}/issued/server.crt"
    - "{{ easy_rsa_pki_path }}/private/server.key"
    - "{{ easy_rsa_pki_path }}/dh.pem"
    - "{{ easy_rsa_pki_path }}/ta.key"

- name: Apply OpenVPN server config
  template:
    src: "{{ openvpn_server_config_name }}"
    dest: /etc/openvpn/server.conf

- name: Start OpenVPN
  systemd:
    name: openvpn@server
    state: started
    enabled: yes

- name: Create client config
  template:
    src: "{{ openvpn_client_config_name }}"
    dest: "client.ovpn"
